### ISSUE TITLE
Kick the tyres

### ISSUE THREAD

**Issue by mdub** [mdub/kafka-playtime#5]
Make kafka do something. Anything.

**Comment by mdub** [comment]
With the help of the [NOTES](https://github.com/kubernetes/charts/blob/master/incubator/kafka/templates/NOTES.txt) on the `incubator/kafka` Helm chart, we got a couple of things working on our GKE-hosted Kafka install (see #1).

Deploying:

```
apiVersion: v1
kind: Pod
metadata:
  name: testclient
  namespace: default
spec:
  containers:
  - command:
    - sh
    - -c
    - exec tail -f /dev/null
    image: confluentinc/cp-kafka:4.0.0
    imagePullPolicy: IfNotPresent
    name: kafka
```

then:

```
kubectl exec testclient -- /usr/bin/kafka-topics --zookeeper singing-toucan-zookeeper:2181 --list
kubectl exec testclient -- /usr/bin/kafka-topics --zookeeper singing-toucan-zookeeper:2181 --topic test1 --create --partitions 1 --replication-factor 1
kubectl exec -ti testclient -- /usr/bin/kafka-console-consumer --bootstrap-server singing-toucan-kafka:9092 --topic test1 --from-beginning
```

then:

```
kubectl exec -ti testclient -- /usr/bin/kafka-console-producer --broker-list singing-toucan-kafka-headless:9092 --topic test1
```
